In [ ]:
'''
EJERCICIO 1
Crea 3 nuevos arrays
    - Array de tipo entero que contenga solo los números impares del 1 al 100
    - Array de tipo cadena con tu nombre y apellidos
    - Array de tipo fecha, que contenga todos los días comprendidos desde el 01Enero2020 al 04Febrero2020'''

In [35]:
import numpy as np
array_entero = np.arange(1,100,2)
array_entero

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [36]:
array_cadena = np.array(['Iván ', 'Perez ', 'Gutiérrez'])
array_cadena

array(['Iván ', 'Perez ', 'Gutiérrez'], dtype='<U9')

In [34]:
array_fecha = np.arange('2020-01-01', '2020-02-04', dtype = 'datetime64[D]')
array_fecha

array(['2020-01-01', '2020-01-02', '2020-01-03', '2020-01-04',
       '2020-01-05', '2020-01-06', '2020-01-07', '2020-01-08',
       '2020-01-09', '2020-01-10', '2020-01-11', '2020-01-12',
       '2020-01-13', '2020-01-14', '2020-01-15', '2020-01-16',
       '2020-01-17', '2020-01-18', '2020-01-19', '2020-01-20',
       '2020-01-21', '2020-01-22', '2020-01-23', '2020-01-24',
       '2020-01-25', '2020-01-26', '2020-01-27', '2020-01-28',
       '2020-01-29', '2020-01-30', '2020-01-31', '2020-02-01',
       '2020-02-02', '2020-02-03'], dtype='datetime64[D]')

In [ ]:
'''
EJERCICIO 2
Recupera los últimos 10 elementos del array de impares'''

In [54]:
recuperar_dig = array_entero[:-11:-1]
recuperar_dig

array([99, 97, 95, 93, 91, 89, 87, 85, 83, 81])

In [ ]:
'''
EJERCICIO 3
Recorre el array de fechas, y genera un nuevo array que contenga unicamente los laborales'''

In [71]:
laborales = array_fecha[np.is_busday(array_fecha)]
laborales

array(['2020-01-01', '2020-01-02', '2020-01-03', '2020-01-06',
       '2020-01-07', '2020-01-08', '2020-01-09', '2020-01-10',
       '2020-01-13', '2020-01-14', '2020-01-15', '2020-01-16',
       '2020-01-17', '2020-01-20', '2020-01-21', '2020-01-22',
       '2020-01-23', '2020-01-24', '2020-01-27', '2020-01-28',
       '2020-01-29', '2020-01-30', '2020-01-31', '2020-02-03'],
      dtype='datetime64[D]')

In [ ]:
'''
EJERCICIO 4
Generar la matriz ( se muestra en el video ). ¿De que tipo es? Luego, implementa una máscara a todos los números de la matriz mayores o iguales a 10.'''

In [81]:
A = np.matrix([[10,1,8,4],[3,7,2,1],[0,2,20,12]])
A.dtype

dtype('int64')

In [80]:
A

matrix([[10,  1,  8,  4],
        [ 3,  7,  2,  1],
        [ 0,  2, 20, 12]])

In [77]:
import numpy.ma as ma
mask = ma.masked_greater_equal(A, 10)
mask

masked_matrix(
  data=[[--, 1, 8, 4],
        [3, 7, 2, 1],
        [0, 2, --, --]],
  mask=[[ True, False, False, False],
        [False, False, False, False],
        [False, False,  True,  True]],
  fill_value=999999)

In [ ]:
'''
EJERCICIO 5
Crea dos fechas, la primera de ellas sera tu fecha de nacimiento, y la segunda, la de un familiar o amigo tuyo.
    - ¿Que diferencia en horas hay entre las dos fechas?
    - ?Cuál sería tu fecha de nacimiento si hubieras nacido 236 horas antes.'''

In [89]:
fecha1 = np.datetime64('1998-04-14')
fecha2 = np.datetime64('2001-09-11')

diferencia = fecha1 - fecha2
diferencia

np.timedelta64(-1246,'D')

In [93]:
np.timedelta64(diferencia, 'h')

np.timedelta64(-29904,'h')

In [103]:
fecha1 - np.timedelta64(236, 'h')

np.datetime64('1998-04-04T04','h')