In [2]:
import numpy as np
import numpy.ma as ma

In [3]:
x = np.array([1,2,3,-1,4])
x

array([ 1,  2,  3, -1,  4])

In [4]:
mask_array = ma.masked_array(x, mask = [0,0,0,1,0])
mask_array

masked_array(data=[1, 2, 3, --, 4],
             mask=[False, False, False,  True, False],
       fill_value=999999)

In [5]:
x.min()

np.int64(-1)

In [33]:
mask_array.min()

np.int64(1)

In [8]:
x = ma.array([1,2,3,-1,4], mask = [0,0,0,1,0])
x

masked_array(data=[1, 2, 3, --, 4],
             mask=[False, False, False,  True, False],
       fill_value=999999)

In [9]:
x.compressed()

array([1, 2, 3, 4])

In [11]:
x.mask = True
x

masked_array(data=[--, --, --, --, --],
             mask=[ True,  True,  True,  True,  True],
       fill_value=999999,
            dtype=int64)

In [12]:
x.mask = False
x

masked_array(data=[1, 2, 3, -1, 4],
             mask=[False, False, False, False, False],
       fill_value=999999)

In [13]:
x.mask = [0,0,0,1,0]
x

masked_array(data=[1, 2, 3, --, 4],
             mask=[False, False, False,  True, False],
       fill_value=999999)

In [14]:
x[0] is ma.masked

False

In [21]:
x.filled(0)

array([1, 2, 3, 0, 4])

In [24]:
x = np.array([1,2,3,-1,4])
x

array([ 1,  2,  3, -1,  4])

In [25]:
ma.masked_equal(x, 4)

masked_array(data=[1, 2, 3, -1, --],
             mask=[False, False, False, False,  True],
       fill_value=4)

In [26]:
ma.masked_not_equal(x, 2)

masked_array(data=[--, 2, --, --, --],
             mask=[ True, False,  True,  True,  True],
       fill_value=999999)

In [27]:
ma.masked_where(x<2, x)

masked_array(data=[--, 2, 3, --, 4],
             mask=[ True, False, False,  True, False],
       fill_value=999999)

In [29]:
ma.masked_greater_equal(x, 2)

masked_array(data=[1, --, --, -1, --],
             mask=[False,  True,  True, False,  True],
       fill_value=999999)

In [30]:
ma.masked_less_equal(x, 2)

masked_array(data=[--, --, 3, --, 4],
             mask=[ True,  True, False,  True, False],
       fill_value=999999)

In [31]:
ma.masked_inside(x, 1, 3)

masked_array(data=[--, --, --, -1, 4],
             mask=[ True,  True,  True, False, False],
       fill_value=999999)