In [2]:
import numpy as np

In [2]:
#### Dimensiones del array

In [4]:
a = np.array([[1,2,3,4],[4,3,2,1]])
a.shape

(2, 4)

In [5]:
a

array([[1, 2, 3, 4],
       [4, 3, 2, 1]])

In [6]:
a.reshape(4,2)

array([[1, 2],
       [3, 4],
       [4, 3],
       [2, 1]])

In [7]:
a.ravel()

array([1, 2, 3, 4, 4, 3, 2, 1])

In [8]:
a

array([[1, 2, 3, 4],
       [4, 3, 2, 1]])

In [9]:
a.T

array([[1, 4],
       [2, 3],
       [3, 2],
       [4, 1]])

In [10]:
#### Tipos de array

In [11]:
np.asarray([1,2,3,4], dtype=np.int8)

array([1, 2, 3, 4], dtype=int8)

In [15]:
a = [1,2,3,4, np.nan]
np.asarray(a)

array([ 1.,  2.,  3.,  4., nan])

In [17]:
np.asarray_chkfinite(a)

ValueError: array must not contain infs or NaNs

In [19]:
np.repeat(a=99, repeats=10).reshape(2,5)

array([[99, 99, 99, 99, 99],
       [99, 99, 99, 99, 99]])

In [24]:
a = np.array([[1,2,3,4],[1,2,3,4]])
b = np.array([[4,3,2,1]])

print(a.shape)
print(b.shape)

(2, 4)
(1, 4)


In [ ]:
#### Unión de arrays

In [25]:
np.concatenate((a,b), axis=0)

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [4, 3, 2, 1]])

In [28]:
#Si se aplica axis 1 directamente da error por dimensiones, con la .T se ponen en vertical y entonces ya se puede
np.concatenate((a.T,b.T), axis=1)

array([[1, 1, 4],
       [2, 2, 3],
       [3, 3, 2],
       [4, 4, 1]])

In [35]:
a = np.array([1,2,3,4])
b = np.array([4,3,2,1])

np.stack((a,b), axis=1)

array([[1, 4],
       [2, 3],
       [3, 2],
       [4, 1]])

In [ ]:
#### División de arrays

In [3]:
a = np.arange(0,20)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [4]:
np.split(a, indices_or_sections=4)

[array([0, 1, 2, 3, 4]),
 array([5, 6, 7, 8, 9]),
 array([10, 11, 12, 13, 14]),
 array([15, 16, 17, 18, 19])]

In [6]:
np.split(a, [3,5,10,16])

[array([0, 1, 2]),
 array([3, 4]),
 array([5, 6, 7, 8, 9]),
 array([10, 11, 12, 13, 14, 15]),
 array([16, 17, 18, 19])]

In [ ]:
### Añadir y eliminar elementos de un array

In [8]:
a = np.array([1,2,3,4])
np.insert(a, obj=4, values=[5,6])

array([1, 2, 3, 4, 5, 6])

In [9]:
np.insert(a, obj=1, values=[5,6])

array([1, 5, 6, 2, 3, 4])

In [10]:
np.append(a, [5,6])

array([1, 2, 3, 4, 5, 6])

In [11]:
np.delete(a, obj=3)

array([1, 2, 3])

In [13]:
a= np.array([0,0,0,0,1,2,3,4,0,45,0,0,0])
np.trim_zeros(a) #Elimina ceros al principio y al final

array([ 1,  2,  3,  4,  0, 45])

In [15]:
a = np.array([1,1,2,2,3,4,4,5,6,6,7])
np.unique(a)

array([1, 2, 3, 4, 5, 6, 7])