In [1]:
import numpy as np

In [4]:
a = np.array([1,2,3,4], dtype = np.int_)
a

array([1, 2, 3, 4])

In [5]:
a.dtype

dtype('int64')

In [7]:
bool_array = np.array([[1,0,0,1], [0,1,1,0]], dtype = np.bool)
bool_array

array([[ True, False, False,  True],
       [False,  True,  True, False]])

In [10]:
char_array = np.array(['a', 'b', 'c'], dtype = np.chararray)
char_array

C:\Users\P1r7h4xX\AppData\Local\Temp\ipykernel_18140\3506859648.py:1: DeprecationWarning: `np.chararray` is deprecated and will be removed from the main namespace in the future. Use an array with a string or bytes dtype instead.
  char_array = np.array(['a', 'b', 'c'], dtype = np.chararray)


array(['a', 'b', 'c'], dtype=object)

In [12]:
from sys import getsizeof

a = np.array([1,2,3,4], dtype = np.int8)
b = np.array([1,2,3,4], dtype = np.int64)

print("A: ", getsizeof(a))
print("B: ", getsizeof(b))

A:  116
B:  144


In [13]:
a.dtype.type is np.int8

True

In [14]:
np.nan

nan

In [15]:
np.isnan(np.nan)

np.True_

In [17]:
np.array([1,2,3, np.nan, 4])

array([ 1.,  2.,  3., nan,  4.])

In [20]:
m = np.matrix('1 2 3 ; 4 5 6', dtype = np.float16)
m

matrix([[1., 2., 3.],
        [4., 5., 6.]], dtype=float16)

In [23]:
a = np.array([[1, 2, 3], [4, 5, 6]], dtype = np.float16)
a

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float16)

In [24]:
ma = np.asmatrix(a)
ma

matrix([[1., 2., 3.],
        [4., 5., 6.]], dtype=float16)