In [1]:
import numpy as np
import numpy.ma as ma

In [5]:
a = np.array([0,1,2,3,4,5,6,7,8,9])
b = np.array([False, False, False, False, False,  True,  True,  True,  True, True])
a[b]

array([5, 6, 7, 8, 9])

In [8]:
a = np.array([2.2,3,4], dtype=float)
a

array([2.2, 3. , 4. ])

In [9]:
a.dtype

dtype('float64')

In [10]:
np.datetime64('2020') == np.datetime64('2020-01-01')

np.True_

In [11]:
a = np.arange(10)
a.reshape((2,5))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [12]:
a = np.array([0,1,2,3,4,5,6,7,8,9])
a[9::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [13]:
np.datetime64('2020-03-14T11') == np.datetime64('2020-03-14T11:00:00.00')

np.True_

In [15]:
x = np.array([2,3,4])
x[0] is ma.masked

False

In [16]:
a = np.array([0,1,2,3,4,5,6,7,8,9])
print(a[0:8:3])

[0 3 6]
