In [3]:
import numpy as np

In [7]:
array1 = np.array([1,2,3,4,5,6], dtype='int')

In [8]:
type(array1)

numpy.ndarray

In [12]:
array2 = np.array([[1,2,3],[4,5,6]], ndmin = 2)
array2

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
array3 = np.array([1,2,3], dtype = 'complex')
array3

array([1.+0.j, 2.+0.j, 3.+0.j])

In [4]:
array4 = np.zeros(5)
array4

array([0., 0., 0., 0., 0.])

In [5]:
np.ones(3)

array([1., 1., 1.])

In [6]:
np.ones((5,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [7]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [10]:
a = np.arange(0,10)
a.reshape((2,5))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [18]:
a.reshape((5,2))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [19]:
b = np.arange(0,15)
b.reshape((3,5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])