In [1]:
import numpy as np

In [ ]:
### Ejercicio 1

In [ ]:
'''
Genera un array que contenga 25 elementos entre 0 y 99 siguiendo una distribución lineal. Luego transforma ese array en una matriz 5x5. 
¿Cuál es la diagonal de la matriz? ¿Y la diagonal justo superior?'''

In [48]:
a = np.linspace(start=0, stop=100, num=25, endpoint=False)
a

array([ 0.,  4.,  8., 12., 16., 20., 24., 28., 32., 36., 40., 44., 48.,
       52., 56., 60., 64., 68., 72., 76., 80., 84., 88., 92., 96.])

In [49]:
m = a.reshape(5,5)
m

array([[ 0.,  4.,  8., 12., 16.],
       [20., 24., 28., 32., 36.],
       [40., 44., 48., 52., 56.],
       [60., 64., 68., 72., 76.],
       [80., 84., 88., 92., 96.]])

In [51]:
np.diag(m)

array([ 0., 24., 48., 72., 96.])

In [54]:
np.diag(m, k = 1)

array([ 4., 28., 52., 76.])

In [ ]:
#Ejercicio 2

In [ ]:
'''
Crea un array de 4x5 con el valor repetido 5. Une esa matriz a la anteior para conseguir 2 nuevas matrices, una de 5x9 y otra de 9x5.
'''

In [56]:
m2 = np.full(shape=(4,5), fill_value=5)
m2

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [62]:
m3 = np.concatenate((m,m2), axis=0)
m3

array([[ 0.,  4.,  8., 12., 16.],
       [20., 24., 28., 32., 36.],
       [40., 44., 48., 52., 56.],
       [60., 64., 68., 72., 76.],
       [80., 84., 88., 92., 96.],
       [ 5.,  5.,  5.,  5.,  5.],
       [ 5.,  5.,  5.,  5.,  5.],
       [ 5.,  5.,  5.,  5.,  5.],
       [ 5.,  5.,  5.,  5.,  5.]])

In [69]:
m4 = np.concatenate((m,m2.T), axis=1)
m4

array([[ 0.,  4.,  8., 12., 16.,  5.,  5.,  5.,  5.],
       [20., 24., 28., 32., 36.,  5.,  5.,  5.,  5.],
       [40., 44., 48., 52., 56.,  5.,  5.,  5.,  5.],
       [60., 64., 68., 72., 76.,  5.,  5.,  5.,  5.],
       [80., 84., 88., 92., 96.,  5.,  5.,  5.,  5.]])

In [ ]:
#Ejercicio 3

In [ ]:
'''
Teniendo el array inicial, se deben realizar las operaciones necesarias para obtener el array:
- array(['Este', 'Es', 'Un', 'Curso', 'De', 'Open', 'Webinars'], dtype='U12')
¿Que elementos del array comienzan por E?'''

In [143]:
a = np.array(['        este es un curso de openwebinars       '], dtype='<U41')
a

array(['        este es un curso de openwebinars '], dtype='<U41')

In [144]:
a1 = np.char.strip(a)
a1

array(['este es un curso de openwebinars'], dtype='<U41')

In [147]:
a2 = np.char.split(a1,sep=' ')
a2 = np.array(a2[0])
a2

array(['este', 'es', 'un', 'curso', 'de', 'openwebinars'], dtype='<U12')

In [148]:
a3 = np.char.capitalize(a2)
a3

array(['Este', 'Es', 'Un', 'Curso', 'De', 'Openwebinars'], dtype='<U12')

In [159]:
e = np.char.startswith(a3, prefix='E')
a3[e]

array(['Este', 'Es'], dtype='<U12')

In [ ]:
#Ejercicio 4

In [ ]:
'''
Considerando las matrices A y B:
- Realiza la multiplicación matricial de AxB y BxA ¿Son iguales?
- Realiza la pmultiplicación de la matriz Ax2
- ¿Cuánto es la multiplicación escalar de AxB?¿Y de BxA?'''

In [171]:
A = np.array([[3,1,2],[4,1,3],[2,0,1]])
B = np.array([[2,0,3],[1,1,1],[0,2,4]])

In [172]:
mult = np.dot(A,B)
mult

array([[ 7,  5, 18],
       [ 9,  7, 25],
       [ 4,  2, 10]])

In [173]:
mult_inv = np.dot(B,A)
mult_inv

array([[12,  2,  7],
       [ 9,  2,  6],
       [16,  2, 10]])

In [174]:
dos = np.dot(A,2)
dos

array([[6, 2, 4],
       [8, 2, 6],
       [4, 0, 2]])

In [175]:
esc1 = np.vdot(A,B)
esc1

np.int64(24)

In [176]:
esc2 = np.vdot(B,A)
esc2

np.int64(24)

In [ ]:
#Ejercicio 5

In [ ]:
'''
Usando la matriz A:
- A^3
- Determinante de A
- Resolver la ecuación Ax = y, siendo y [3,2,5]'''

In [180]:
cubo = np.linalg.matrix_power(A,3)
cubo

array([[ 89,  21,  57],
       [114,  27,  73],
       [ 42,  10,  27]])

In [178]:
det = np.linalg.det(A)
det

np.float64(1.0)

In [179]:
y = np.array([3,2,5])
ecu = np.linalg.solve(A,y)
ecu

array([ 6., -1., -7.])