In [1]:
import numpy as np

In [2]:
### Funciones relacionadas con el orden

In [3]:
a = np.array([2,5,6,10])
np.min(a)

np.int64(2)

In [4]:
np.max(a)

np.int64(10)

In [7]:
b = np.arange(12).reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [6]:
np.min(b, axis = 0)

array([0, 1, 2, 3])

In [8]:
np.min(b, axis = 1)

array([0, 4, 8])

In [9]:
np.max(b, axis = 1)

array([ 3,  7, 11])

In [10]:
c = np.arange(0, 101)
c

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

In [11]:
np.percentile(c, q = 11)

np.float64(11.0)

In [20]:
d = np.arange(10, 400, 2)
d

array([ 10,  12,  14,  16,  18,  20,  22,  24,  26,  28,  30,  32,  34,
        36,  38,  40,  42,  44,  46,  48,  50,  52,  54,  56,  58,  60,
        62,  64,  66,  68,  70,  72,  74,  76,  78,  80,  82,  84,  86,
        88,  90,  92,  94,  96,  98, 100, 102, 104, 106, 108, 110, 112,
       114, 116, 118, 120, 122, 124, 126, 128, 130, 132, 134, 136, 138,
       140, 142, 144, 146, 148, 150, 152, 154, 156, 158, 160, 162, 164,
       166, 168, 170, 172, 174, 176, 178, 180, 182, 184, 186, 188, 190,
       192, 194, 196, 198, 200, 202, 204, 206, 208, 210, 212, 214, 216,
       218, 220, 222, 224, 226, 228, 230, 232, 234, 236, 238, 240, 242,
       244, 246, 248, 250, 252, 254, 256, 258, 260, 262, 264, 266, 268,
       270, 272, 274, 276, 278, 280, 282, 284, 286, 288, 290, 292, 294,
       296, 298, 300, 302, 304, 306, 308, 310, 312, 314, 316, 318, 320,
       322, 324, 326, 328, 330, 332, 334, 336, 338, 340, 342, 344, 346,
       348, 350, 352, 354, 356, 358, 360, 362, 364, 366, 368, 37

In [21]:
np.percentile(d, q = 11)

np.float64(52.68)

In [24]:
np.quantile(d, q = 0.25)

np.float64(107.0)

In [18]:
### Medias y varianzas

In [25]:
c = np.arange(0, 101)
np.mean(c)

np.float64(50.0)

In [26]:
np.median(c)

np.float64(50.0)

In [27]:
np.average(c)

np.float64(50.0)

In [29]:
e = np.arange(12).reshape(4,3)
e

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [31]:
np.mean(e, axis = 1)

array([ 1.,  4.,  7., 10.])

In [32]:
np.mean(e, axis = 0)

array([4.5, 5.5, 6.5])

In [33]:
np.std(e)

np.float64(3.452052529534663)

In [35]:
np.var(e, axis=1)

array([0.66666667, 0.66666667, 0.66666667, 0.66666667])