In [1]:
import numpy as np

In [2]:
#Ejercicio 1

In [ ]:
'''
Usando el array a continuación:
- ¿Hay algún valor múltiplo de 7?
- Devuelve un array con todos los nº menores de 40 o múltiplos de 7?'''

In [4]:
a = np.array([2,5,4,2,49,34,59,21,45,6,105])
a

array([  2,   5,   4,   2,  49,  34,  59,  21,  45,   6, 105])

In [6]:
mult7 = a % 7 == 0
a[mult7]

array([ 49,  21, 105])

In [21]:
menores = np.logical_or(a < 40, mult7)
res = a[menores]
res

array([  2,   5,   4,   2,  49,  34,  21,   6, 105])

In [13]:
# Ejercicio 2

In [ ]:
'''
Usando el array anterior:
- Producto de todos los valores
- Convierte el array en una matriz 3x3 y realiza la suma por filas
- Calcula el log10 de cada elemento de la matriz que acabas de crear'''

In [22]:
res

array([  2,   5,   4,   2,  49,  34,  21,   6, 105])

In [23]:
prod = np.prod(res)
prod

np.int64(1763294400)

In [25]:
b = res.reshape(3,3)
b

array([[  2,   5,   4],
       [  2,  49,  34],
       [ 21,   6, 105]])

In [32]:
suma = np.sum(b, axis=1)
suma

array([ 11,  85, 132])

In [34]:
np.log10(b)

array([[0.30103   , 0.69897   , 0.60205999],
       [0.30103   , 1.69019608, 1.53147892],
       [1.32221929, 0.77815125, 2.0211893 ]])

In [ ]:
# Ejercicio 3

In [ ]:
'''
Usando la matriz anterior:
- Suma de la matriz mas el vector
- División de ambos, ¿qué ocurre? Modificar el valor raro por 0
- Valos máximo de la matriz resultado de la división, ¿y por filas?, ¿y columnas?'''

In [35]:
b

array([[  2,   5,   4],
       [  2,  49,  34],
       [ 21,   6, 105]])

In [36]:
a = np.array([0,3,5])
a

array([0, 3, 5])

In [39]:
suma = np.add(b, a)
suma

array([[  2,   8,   9],
       [  2,  52,  39],
       [ 21,   9, 110]])

In [42]:
div = np.divide(suma, a)
div

C:\Users\P1r7h4xX\AppData\Local\Temp\ipykernel_21712\4166734561.py:1: RuntimeWarning: divide by zero encountered in divide
  div = np.divide(suma, a)


array([[        inf,  2.66666667,  1.8       ],
       [        inf, 17.33333333,  7.8       ],
       [        inf,  3.        , 22.        ]])

In [46]:
for i in div:
    i[0] = 0
div

array([[ 0.        ,  2.66666667,  1.8       ],
       [ 0.        , 17.33333333,  7.8       ],
       [ 0.        ,  3.        , 22.        ]])

In [47]:
np.max(div)

np.float64(22.0)

In [48]:
np.max(div, axis = 0)

array([ 0.        , 17.33333333, 22.        ])

In [49]:
np.max(div, axis = 1)

array([ 2.66666667, 17.33333333, 22.        ])

In [50]:
#Ejercicio 4

In [ ]:
'''
Calcular:
- Media y mediana
- Valor del 3er cuartil
- Valor del percentil 25 y 50. ¿Con qué valor coincide este último?
- Desviación estándar y varianza'''

In [51]:
a = np.array([44, 28, 8, 34, 34, 26, 32, 12, 28, 6, 19, 12, 46, 20, 20, 49, 18,
              10,15,15,43,3,17,33,27,10,18,2,3,3,35,35,21,17])
a

array([44, 28,  8, 34, 34, 26, 32, 12, 28,  6, 19, 12, 46, 20, 20, 49, 18,
       10, 15, 15, 43,  3, 17, 33, 27, 10, 18,  2,  3,  3, 35, 35, 21, 17])

In [55]:
media = np.mean(a)
media = np.round(media,2)
media

np.float64(21.85)

In [56]:
mediana = np.median(a)
mediana

np.float64(19.5)

In [57]:
cuartil = np.quantile(a, q = 0.75)
cuartil

np.float64(32.75)

In [59]:
percentil25 = np.percentile(a, q = 25)
percentil25

np.float64(12.0)

In [60]:
percentil50 = np.percentile(a, q = 50)
percentil50

np.float64(19.5)

In [64]:
de = np.std(a)
de = np.round(de,2)
de

np.float64(13.07)

In [66]:
var = np.var(a)
var = np.round(var,2)
var

np.float64(170.89)

In [70]:
np.round(np.sqrt(np.var(a)),2) #La std es la raiz cuadrada de la var, por tanto:

np.float64(13.07)