In [1]:
import numpy as np

In [2]:
a = np.array([2,3,4,5])
np.all(a > 10)

np.False_

In [3]:
np.any(a < 3)

np.True_

In [4]:
np.logical_and(a > 2, a < 4)

array([False,  True, False, False])

In [5]:
np.logical_or(a > 2, a < 4)

array([ True,  True,  True,  True])

In [9]:
b = np.allclose([1e10, 1e-7], [1.00001e10, 1.000001e-7], rtol=0.00001)
b

True

In [11]:
c = np.isclose([1e10, 1e-7], [1.001e10, 1.000001e-7], rtol=0.00001)
c

array([False,  True])

In [12]:
np.array_equal(np.array([1,2,3]), np.array([1,2,4]))

False

In [13]:
np.greater_equal(np.array([1,2,3]), np.array([1,2,4]))

array([ True,  True, False])

In [15]:
np.less_equal(np.array([2,2,3]), np.array([1,2,4]))

array([False,  True,  True])