In [1]:
import numpy as np

In [3]:
a = np.array(['a','b','c'], dtype=str)
b = np.array(['d','e','f'], dtype=str)

np.char.add(a,b)

array(['ad', 'be', 'cf'], dtype='<U2')

In [4]:
np.char.multiply(a, [2,3,4])

array(['aa', 'bbb', 'cccc'], dtype='<U4')

In [6]:
nombres = (['maria', 'antonio', 'lucía'])
np.char.capitalize(nombres)

array(['Maria', 'Antonio', 'Lucía'], dtype='<U7')

In [7]:
np.char.replace(nombres, 'mar', 'sof')

array(['sofia', 'antonio', 'lucía'], dtype='<U7')

In [8]:
nombre = np.array(['Mi nombre es Alojote Loramento'])
np.char.split(nombre, sep=' ')

array([list(['Mi', 'nombre', 'es', 'Alojote', 'Loramento'])], dtype=object)

In [10]:
c = np.array(['   Hola ', '   adios    '])
np.char.strip(c)

array(['Hola', 'adios'], dtype='<U12')

In [ ]:
#### Comparación

In [12]:
a = np.array(['A','B','C'], dtype = str)
b = np.array(['D','B','F'], dtype = str)

np.char.equal(a,b)

array([False,  True, False])

In [13]:
np.char.not_equal(a,b)

array([ True, False,  True])

In [14]:
np.char.greater_equal(a,b)

array([False,  True, False])

In [15]:
np.char.less_equal(a,b)

array([ True,  True,  True])

### Información de cadenas

In [16]:
c = np.array(['Hola','Adios'])
np.char.endswith(c, suffix='ios')

array([False,  True])

In [17]:
np.char.startswith(c, prefix='Ad')

array([False,  True])

In [18]:
c = np.array(['HOLA', 'adios'])
np.char.islower(c)

array([False,  True])

In [19]:
np.char.isupper(c)

array([ True, False])

In [20]:
c = np.array(['HOLA', 'adios', '1230'])
np.char.isdigit(c)

array([False, False,  True])

In [21]:
c[np.char.isdigit(c)]

array(['1230'], dtype='<U5')