In [1]:
import numpy as np

In [9]:
a = np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
a[0]

np.int64(1)

In [11]:
a[4]

np.int64(5)

In [12]:
a.shape

(10,)

In [13]:
a[0:9]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
a[0:9:2]

array([1, 3, 5, 7, 9])

In [15]:
a[-2:10]

array([ 9, 10])

In [16]:
a[9::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [17]:
b = np.array([[1,2,3],[4,5,6]], dtype = np.int8)
b

array([[1, 2, 3],
       [4, 5, 6]], dtype=int8)

In [19]:
b[1][2]

np.int8(6)

In [20]:
b[1,2]

np.int8(6)

In [21]:
b[1,0:2]

array([4, 5], dtype=int8)

In [22]:
m = np.matrix(b)
m

matrix([[1, 2, 3],
        [4, 5, 6]], dtype=int8)

In [23]:
m[0,1] + m[1,0]

np.int8(6)

In [25]:
x = np.array([[4,3], [np.nan, 2], [np.nan, np.nan]])
x

array([[ 4.,  3.],
       [nan,  2.],
       [nan, nan]])

In [26]:
x[np.isnan(x)]

array([nan, nan, nan])

In [27]:
x[~np.isnan(x)]

array([4., 3., 2.])

In [28]:
y = np.arange(10)
y

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
y > 4

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [30]:
y[y > 4]

array([5, 6, 7, 8, 9])

In [31]:
y[y%2==0]

array([0, 2, 4, 6, 8])

In [32]:
c = np.array(['OWebinars', 'Machine Learning', 'Numpy'])
c

array(['OWebinars', 'Machine Learning', 'Numpy'], dtype='<U16')

In [33]:
c[c == 'Numpy']

array(['Numpy'], dtype='<U16')

In [34]:
d = np.array([False, False, True])
d

array([False, False,  True])

In [35]:
c[d]

array(['Numpy'], dtype='<U16')

In [36]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [38]:
for i in a:
    print(i)

1
2
3
4
5
6
7
8
9
10


In [41]:
for valor in np.nditer(a):
    print(valor)

1
2
3
4
5
6
7
8
9
10
