In [2]:
import numpy as np

In [2]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [3]:
np.eye(4, k=1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [4]:
np.eye(4, k= -1)

array([[0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [5]:
np.identity(4, dtype='int8')

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]], dtype=int8)

In [6]:
np.full(shape=(4,4), fill_value=99)

array([[99, 99, 99, 99],
       [99, 99, 99, 99],
       [99, 99, 99, 99],
       [99, 99, 99, 99]])

In [7]:
np.full(shape=(4,4), fill_value=[10,20,30,40])

array([[10, 20, 30, 40],
       [10, 20, 30, 40],
       [10, 20, 30, 40],
       [10, 20, 30, 40]])

In [9]:
#### Creación desde datos existentes

In [10]:
np.fromstring('1 2 3 4', sep=' ')

array([1., 2., 3., 4.])

In [12]:
datos = np.loadtxt('./datos.txt', delimiter=' ')
datos

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.]])

In [3]:
np.linspace(start=1, stop=10, num=5) #Crea un array de distribución lineal

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [14]:
np.linspace(start=1, stop=10, num=5, endpoint=False, retstep=True)

(array([1. , 2.8, 4.6, 6.4, 8.2]), np.float64(1.8))

In [16]:
np.linspace(start=1, stop=10, num=5, endpoint=False, retstep=False)

array([1. , 2.8, 4.6, 6.4, 8.2])

In [18]:
np.linspace(start=2, stop=3.5, num=10)

array([2.        , 2.16666667, 2.33333333, 2.5       , 2.66666667,
       2.83333333, 3.        , 3.16666667, 3.33333333, 3.5       ])

In [ ]:
'''Logspace realiza una función logarítmica, es decir, son los números vistos en linspace anterior, pero:
- 10 ** 2 = 100
- 10 ** 2.16666667 = 146.77992676
- 10 ** 2.33333333 = 215.443469 
etc'''

In [17]:
np.logspace(start=2, stop=3.5, num=10)

array([ 100.        ,  146.77992676,  215.443469  ,  316.22776602,
        464.15888336,  681.29206906, 1000.        , 1467.79926762,
       2154.43469003, 3162.27766017])

In [ ]:
#### Creación de matrices

In [21]:
a = np.eye(N = 4)
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [22]:
np.diag(a)

array([1., 1., 1., 1.])

In [23]:
np.diag(a, k=-1)

array([0., 0., 0.])

In [24]:
np.diagflat(v = [1,2,3,4,5], k = 0)

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [26]:
# n.tri pone 1 en la diagonal y debajo y el resto 0
np.tri(N = 5, M = 5)

array([[1., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0.],
       [1., 1., 1., 1., 1.]])

In [28]:
np.tri(N = 4, M = 5, k= -1)

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0.]])