In [2]:
import numpy as np

In [6]:
a = np.array([[3,2],[1,3]])
b = np.array([[2,2],[1,2]])
np.dot(a,b)

array([[ 8, 10],
       [ 5,  8]])

In [7]:
np.dot(b,a)

array([[ 8, 10],
       [ 5,  8]])

In [9]:
np.vdot(a,b) #Producto escalar

np.int64(17)

In [11]:
a = np.arange(6).reshape(2,3)
b = np.arange(3)
print(a)
print(b)

[[0 1 2]
 [3 4 5]]
[0 1 2]


In [13]:
np.inner(a,b) #Producto interno

array([ 5, 14])

In [15]:
m = np.array([[2,3],[1,4]])
m

array([[2, 3],
       [1, 4]])

In [17]:
np.linalg.matrix_power(m,2) #Producto matricial

array([[ 7, 18],
       [ 6, 19]])

In [ ]:
### Valores propios - Determinantes y vectores propios

In [18]:
m = np.diag([4,3,2,1])
m

array([[4, 0, 0, 0],
       [0, 3, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 1]])

In [20]:
np.linalg.det(m)

np.float64(24.000000000000004)

In [24]:
a = np.array([[3,1],[1,2]])
b = np.array([9,8])
print(a)
print(b)

[[3 1]
 [1 2]]
[9 8]


In [25]:
x = np.linalg.solve(a,b) #Resolución de ecuaciones
x

array([2., 3.])

In [ ]:
''' Esto sería:
- 3 * x0 + 1 * x1 = 9
- 1 * x0 + 2 * x1 = 8

Es decir, si x0 fuera 2 y x1 fuera 3 daría 9, y 8:
- 3*2->6 + 1*3->3 = 9
- 1*2->2 + 2*3->6 = 8'''