In [1]:
import numpy as np

In [2]:
### Redondeo

In [4]:
a = 2.49264
a

2.49264

In [5]:
np.round(a,2)

np.float64(2.49)

In [6]:
np.round(a,1)

np.float64(2.5)

In [9]:
array = np.array([1.435, 13.1435, 4.0916])
np.round(array,2)

array([ 1.44, 13.14,  4.09])

In [10]:
np.floor(array)

array([ 1., 13.,  4.])

In [11]:
np.ceil(array)

array([ 2., 14.,  5.])

In [12]:
### Sumas y productos

In [13]:
b = np.array([2,3,4])
np.prod(b)

np.int64(24)

In [15]:
b = np.array([[2,3,4],[2,2,2]])
np.prod(b, axis = 0)

array([4, 6, 8])

In [16]:
np.prod(b, axis = 1)

array([24,  8])

In [18]:
np.sum(b, axis = 0)

array([4, 5, 6])

In [19]:
np.sum(b, axis = 1)

array([9, 6])

In [20]:
### Exponentes y logaritmos

In [21]:
np.exp(b)

array([[ 7.3890561 , 20.08553692, 54.59815003],
       [ 7.3890561 ,  7.3890561 ,  7.3890561 ]])

In [22]:
np.power(np.e, b)

array([[ 7.3890561 , 20.08553692, 54.59815003],
       [ 7.3890561 ,  7.3890561 ,  7.3890561 ]])

In [24]:
p = np.power(np.e, b)
np.log(p)

array([[2., 3., 4.],
       [2., 2., 2.]])

In [25]:
np.log2(b)

array([[1.       , 1.5849625, 2.       ],
       [1.       , 1.       , 1.       ]])

In [26]:
np.log10(b)

array([[0.30103   , 0.47712125, 0.60205999],
       [0.30103   , 0.30103   , 0.30103   ]])

In [27]:
np.log(0)

C:\Users\P1r7h4xX\AppData\Local\Temp\ipykernel_14176\2933082444.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(0)


np.float64(-inf)

In [28]:
### Operaciones aritméticas

In [30]:
a = np.array([[1,2,3,4], [4,3,2,1]])
b = np.array([4,3,2,1])
np.add(a,b)

array([[5, 5, 5, 5],
       [8, 6, 4, 2]])

In [31]:
np.subtract(a,b)

array([[-3, -1,  1,  3],
       [ 0,  0,  0,  0]])

In [32]:
np.divide(a,b)

array([[0.25      , 0.66666667, 1.5       , 4.        ],
       [1.        , 1.        , 1.        , 1.        ]])